include: package:lint/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_classes_with_only_static_members: true
    avoid_positional_boolean_parameters: true
    cascade_invocations: true
    constant_identifier_names: true
    file_names: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    avoid_print: true
    require_trailing_commas: true
    avoid_empty_else: true
    avoid_field_initializers_in_const_classes: true
    avoid_init_to_null: true
    avoid_returning_null_for_future: true
    null_closures: true
    no_logic_in_create_state: true
    prefer_typing_uninitialized_variables: true
    unnecessary_null_checks: true
    unnecessary_late: true
    library_prefixes: true
    prefer_single_quotes: true
    camel_case_types: true
    non_constant_identifier_names: false
    use_build_context_synchronously: true
    avoid_redundant_argument_values: true
    prefer_const_literals_to_create_immutables: true
    prefer_iterable_whereType: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_const_constructors_in_immutables: true
